### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by pavelk2** [loopj/initials-avatar#4]
Dear @loopj,
The service of avatars generation with initials is of my need currently for the project http://codesign.io. How can I deploy initials-avatar on Heroku? 

BTW - they provide deploy buttons - it would be great to have one here right in the readme file so anybody could deploy initials-avatar for them.

**Comment by loopj** [comment]
Unfortunately Heroku doesn't support imagemagick, which is required for this project.
